import Image from 'next/image'
import Link from 'next/link'
import Head from 'next/head'
import styles from '@/styles/bouquet.module.css'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'

export default function Bouquet(){
    return(
        <>
            <Head>
                <title>cuts of colours</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo/cutsofcolours-logo.png" />
            </Head>
            <main className={styles.main}>
                <Navbar></Navbar>
                <div className={styles.background}>
                    <Image
                        src={"/images/bouquet_background.png"}
                        height={624}
                        width={1440}
                    />
                    <div className={styles.box_background}>
                        <p>flower bouquets are made of <br></br> 100% recycled materials</p>
                    </div>
                </div>
                <div className={styles.seasonal}>
                    <p className={styles.headings}>handcrafted seasonal bouquets</p>
                    <div className={styles.bouquet_row}>
                        <div className={styles.bouquet_column}>
                        <Image
                            className={styles.image_border}
                            src={"/images/bouquet/bouquet_1.jpeg"}
                            width={312}
                            height={320}
                        />
                        <div className={styles.bouquet_desc}>
                            <p>lorem ipsum</p>
                            <p>$$</p>
                        </div>
                        </div>
                        <div className={styles.bouquet_column}>
                        <Image
                            className={styles.image_border}
                            src={"/images/bouquet/bouquet_1.jpeg"}
                            width={312}
                            height={320}
                        />
                        <div className={styles.bouquet_desc}>
                            <p>lorem ipsum</p>
                            <p>$$</p>
                        </div>
                        </div>
                        <div className={styles.bouquet_column}>
                        <Image
                            className={styles.image_border}
                            src={"/images/bouquet/bouquet_1.jpeg"}
                            width={312}
                            height={320}
                        />
                        <div className={styles.bouquet_desc}>
                            <p>lorem ipsum</p>
                            <p>$$</p>
                        </div>
                        </div>
                    </div>
                    <div className={styles.bouquet_row}>
                        <div className={styles.bouquet_column}>
                        <Image
                            className={styles.image_border}
                            src={"/images/bouquet/bouquet_1.jpeg"}
                            width={312}
                            height={320}
                        />
                        <div className={styles.bouquet_desc}>
                            <p>lorem ipsum</p>
                            <p>$$</p>
                        </div>
                        </div>
                        <div className={styles.bouquet_column}>
                        <Image
                            className={styles.image_border}
                            src={"/images/bouquet/bouquet_1.jpeg"}
                            width={312}
                            height={320}
                        />
                        <div className={styles.bouquet_desc}>
                            <p>lorem ipsum</p>
                            <p>$$</p>
                        </div>
                        </div>
                        <div className={styles.bouquet_column}>
                        <Image
                            className={styles.image_border}
                            src={"/images/bouquet/bouquet_1.jpeg"}
                            width={312}
                            height={320}
                        />
                        <div className={styles.bouquet_desc}>
                            <p>lorem ipsum</p>
                            <p>$$</p>
                        </div>
                        </div>
                    </div>
                </div>
                <Footer></Footer>
            </main>
        </>
    )
}