import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import Navbar from '@/components/navbar'
import Footer from '@/components/footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>cuts of colours</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo/cutsofcolours-logo.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin></link>
        <link href="https://fonts.googleapis.com/css2?family=Karla&display=swap" rel="stylesheet"></link>
      </Head>
      <main className={styles.main}>
        <Navbar></Navbar>
        <div className={styles.background}>
          <Image
            src={"/images/home_background.png"}
            height={624}
            width={1440}
            alt='bouquet home background'
          />
          <div className={styles.box_background}>
            <p>we proudly offer handcrafted seasonal bouquets & personalized flower arrangements</p>
          </div>
        </div>
        <div className={styles.seasonal}>
          <p className={styles.headings}>handcrafted seasonal bouquets</p>
          <div className={styles.bouquet_row}>
            <div className={styles.bouquet_column}>
              <Image
                className={styles.image_border}
                src={"/images/bouquet/bouquet_1.jpeg"}
                width={312}
                height={320}
              />
              <div className={styles.bouquet_desc}>
                <p>lorem ipsum</p>
                <p>$$</p>
              </div>
            </div>
            <div className={styles.bouquet_column}>
              <Image
                className={styles.image_border}
                src={"/images/bouquet/bouquet_1.jpeg"}
                width={312}
                height={320}
              />
              <div className={styles.bouquet_desc}>
                <p>lorem ipsum</p>
                <p>$$</p>
              </div>
            </div>
            <div className={styles.bouquet_column}>
              <Image
                className={styles.image_border}
                src={"/images/bouquet/bouquet_1.jpeg"}
                width={312}
                height={320}
              />
              <div className={styles.bouquet_desc}>
                <p>lorem ipsum</p>
                <p>$$</p>
              </div>
            </div>
          </div>
          <div className={styles.view_more}>
            <Link href={"/bouquet"}>
              <button>
                view more
                <Image
                  src={"/icon/next_arrow.svg"}
                  width={24}
                  height={24} 
                />
              </button>
            </Link>
          </div>
        </div>
        <div className={styles.personalized}>
          <p className={styles.headings}>personalized flower arrangements</p>
          <div className={styles.flower_row}>
            <div className={styles.flower_column}>
              <Image
                className={styles.image_border}
                src={"/images/flowers/pink_lily.jpeg"}
                width={312}
                height={320}
              />
              <div className={styles.bouquet_desc}>
                <p>blush pink lily</p>
                <p>$$</p>
              </div>
            </div>
            <div className={styles.flower_column}>
              <Image
                className={styles.image_border}
                src={"/images/flowers/pink_poppy.jpeg"}
                width={312}
                height={320}
              />
              <div className={styles.bouquet_desc}>
                <p>pink poppy</p>
                <p>$$</p>
              </div>
            </div>
            <div className={styles.flower_column}>
              <Image
                className={styles.image_border}
                src={"/images/flowers/peachy_rose.jpeg"}
                width={312}
                height={320}
              />
              <div className={styles.bouquet_desc}>
                <p>pink peachy rose</p>
                <p>$$</p>
              </div>
            </div>
          </div>
          <div className={styles.view_more}>
            <Link href={"/flowers"}>
              <button>
                view more
                <Image
                  src={"/icon/next_arrow.svg"}
                  width={24}
                  height={24} 
                />
              </button>
            </Link>
          </div>
        </div>
        <Footer></Footer>
      </main>
    </>
  )
}
